baseURL = 'https://nicrodalv.github.io'
languageCode = 'español'
paginate = 6
theme= "coHub"
title = 'Holus'
 
[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Productos"
  url= "#gallery"
  weight = 1
  
  [[menu.Main]]
  name = "Acerca de nosotros"
  url= "/about/"
  weight = 2

  [[menu.Main]]
  name = "Contacto"
  url= "/contact/"
  weight = 3

  
  [[menu.Main]]
  name = "Preguntas frecuentes"
  url= "#faq"
  weight = 4
  

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Política de privacidad"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Términos y condiciones"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "blog"
  contactLink = "contact"
  copyright = ""
  formspreeURL = "https://formspree.io/mbjwlead"
  googleAnalytics = "G-JZ95FEWF9K"
  logo = "images/logo.png"
  footerlogo = "images/logosmall.png"
  footerDescription = ""

  [params.address]
  openingDesc = "¡No se olvide de contactarnos!"
  email = "holus.contacto@gmail.com"
  openingHours = ""
  phone = "+54 294 154 241464"

  # Social icons
  # [[params.social]]
  # icon = "ti-facebook"
  # url = "https://www.facebook.com/"
  # weight = 1
  # [[params.social]]
  # icon = "ti-twitter-alt"
  # url = "https://twitter.com/"
  # weight = 2
  # [[params.social]]
  # icon = "ti-dribbble"
  # url = "https://dribbble.com/"
  # weight = 3
  # [[params.social]]
  # icon = "ti-instagram"
  # url = "https://www.instagram.com/"
  # weight = 4
  